version: "3.9"

services:

  cli:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ISA2022
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=LOZINKA
      - MYSQL_ROOT_PASSWORD=LOZINKA
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 50
    # The above healthcheck configuration defines a test that verifies that the MySQL database is fully initialized and ready to accept connections.

  app:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      mysql_server:
        condition: service_healthy
    # The above depends_on configuration specifies that the app container should only start when the MySQL container is healthy.